### ISSUE TITLE
[GraphQL error]: Message: Cannot read property 'workspaceId' of null. Path: updateBlocks.

### ISSUE THREAD

**Issue by stuhlmueller** [oughtinc/mosaic#235]
Happened when I created a workspace that looks like this:

<img width="964" alt="screen shot 2018-10-30 at 1 46 55 pm" src="https://user-images.githubusercontent.com/382515/47749396-4e0d8680-dc4a-11e8-80e0-5a63f1aa4880.png">

**Comment by zjmiller** [comment]
Resolved in 3724c42

All editor components, when unmounting, were attempting to save their contents to the backend database. Currently, the new question form only exists on the frontend. So this error arose whenever the new question form attempted to save its contents to the backend database (since there was no corresponding block in the database).

In the future, we plan to add new questions to the backend database (see https://github.com/oughtinc/mosaic/issues/224) so that questions in progress get saved. We'll need to revisit this then.
