### ISSUE TITLE
Show character counts for expert answer boxes

### ISSUE THREAD

**Issue by andrewschreiber** [oughtinc/mosaic#647]
The biggest piece of UI/UX feedback from the July 30th live experiments was that participants wanted to know how many characters they had used. Although they could copy/paste to an outside tool, we should be able to give them this info inside Mosaic. 

@zjmiller notes we could make use of the existing functionality that shows character counts on pointer tooltips.

Let's discuss how we want the character counter to look. Here is one before/after sketch:

![image](https://user-images.githubusercontent.com/1892071/62251073-82fa6580-b3a3-11e9-847f-ed43e9533fdf.png)

![image](https://user-images.githubusercontent.com/1892071/62251115-960d3580-b3a3-11e9-9ab1-e4e7dd1ff76b.png)

If the workspace count got into the negatives, the counters would turn red. Thoughts? @brachbach @stuhlmueller

**Comment by brachbach** [comment]
Some notes:
- we tell the participants to use something like this: https://chrome.google.com/webstore/detail/word-counter/adgmgllmfhgppfnkmgikgbaniemjdikk?hl=en

so, way easier than using an external site but still annoying

- I think showing user workspace chars remaining is the wrong way to go. Because:
-- honest expert shouldn't really get to know that IMO
-- it shouldn't be that helpful to know -- the judges should always try to keep answers short anyway, and the judge might always ask an additional subquestion

- I think that chars within pointers shouldn't count towards your total

I also, on reflection, still think the value of this is pretty low (I'm saying 2, could see 5)

**Comment by Mati-Roy** [comment]
> I think showing user workspace chars remaining is the wrong way to go. Because:
-- honest expert shouldn't really get to know that IMO

@brachbach , although, especially with MIB, Judges could reliably / consistently pass down their remaining character and sub-Q budget so that HEs have more info on how to spend the characters.

**Comment by Mati-Roy** [comment]
For reference, Erol suggested:
> character count below text boxes would also be useful for experts
and got 5 :heart-eyes:
(source: https://app.slack.com/client/T3L8K3NMT/CKT7N2C83/thread/CKT7N2C83-1566583251.032600)
