### ISSUE TITLE
The app seems to be getting quite slow for participants

### ISSUE THREAD

**Issue by brachbach** [oughtinc/mosaic#743]
Erol Can Akbaba Yesterday at 1:39 PM
This isn't really a bug, but performance is starting to become an issue for me. The load time for listing of previous workspaces is quite long for some time but that doesn't impact my work. Load times for finding a workspace is getting longer and longer - sometimes I refresh the page after a minute or so to get it going.

:+1:
5

https://ought-inc.slack.com/archives/CMPKU3B5F/p1568666376008000

**Comment by brachbach** [comment]
I think it's a pretty high priority to at least understand why things are bogging down.

@zjmiller @andrewschreiber -- my assumption is that now that I've put this on top of the list of priority issues, one of you will grab it soon and look into why things are bogging down

let me know if that's not true

and of course let me or Mati know if you'd like our help figuring out why things are bogging down

**Comment by zjmiller** [comment]
I'm busy with Mosaic2 things until Thurs. You want to take a look @andrewschreiber ? I would start looking at `fetchAllRootWorkspaces` in `server/lib/scheduler/index.ts` and try to limit the initial query to just the relevant root workspaces.

**Comment by brachbach** [comment]
TBC, Thurs (or even next week) would be totally fine IMO -- I just think that this should be the next thing to work on when you guys have time

but also I'm excited for @andrewschreiber to take a look if he wants :)

**Comment by andrewschreiber** [comment]
Yup will definitely take a look at this after Hide Archive and Show Hyperlinks

**Comment by andrewschreiber** [comment]
Took a peak and there is definitely room for optimization without too major of a refactor.

**Comment by brachbach** [comment]
cool. Do you think that, if you did the optimization you're talking about, it would be extremely rare for anyone to have to wait more than a couple seconds for anything to load?

if so, I'm fine with you just going ahead with it

if not, or if you'd like more thoughts on prioritization, could you explain:
1. what things seem to be slow
2. why they're slow
3. what you were thinking you could do to speed them up?

**Comment by andrewschreiber** [comment]
A quick look suggested there indeed is, per Zak's hunch, an opportunity to reduce the number of workspaces queried in the method that currently calls `fetchAllRootWorkspaces`.

I don't have a clear sense as to the scale of that improvement yet. A good next step would be some performance profiling while reproducing the long wait experience.

Do all participants see similar long waits or only some?

**Comment by andrewschreiber** [comment]
![image](https://user-images.githubusercontent.com/1892071/65195778-c92f8500-da34-11e9-86bb-82811740e73b.png)
Looks like slack archives are unreliable, unfortunately

**Comment by brachbach** [comment]
re: Slack archives -- that link works for me, I think it didn't work for you just because you weren't a member of the relevant channel. I just added you to it.

**Comment by brachbach** [comment]
Re: more info --

1. Mostly I just know the info from the Slack thread. (But really there's nothing more than the original post with the 5 thumbs-up)
2. Sometimes when I load a workspace to analyze it, it takes up to like 5-10 seconds. This can be annoying, especially at the high end, but is bearable. Would be nice if it were shorter
3. @Mati-Roy might have more info

**Comment by brachbach** [comment]
Another thing that was slow: loading the trees onto this experiment admin page: https://mosaic.ought.org/e/113 took about 5 seconds

**Comment by andrewschreiber** [comment]
Wanted to write out my understanding here for reference - mostly my own.

The slowest UX that Mosaic1 users face is finding a workspace. It often takes over 15 seconds, sometimes more than a minute. If it takes much longer than a minute or so, the user is recommended to refresh the page. The issue seems to be getting worse as we scale up. My goal is to figure out the bottlenecks and optimize them.

After some investigation using breakpoints, it seems the vast majority of the time (>95%) waiting is due to processing on the server-side, not the client-side. We'll put aside client optimization for now.

More specifically, I've found that the `findNextWorkspace` resolver in `server/lib/schema/index.ts` is a key bottleneck. The resolver's submethods require db calls in proportion to the number of root workspaces and the number of trees per workspace. A candidate for a major cause of slow down as we scale. The database is heavily drafted for this resolver, and I'd like to see if optimizing it ends our regular breach of 5% response failure rate during peak activity hours.

`findNextWorkspace` calls `assignNextWorkspace` from `server/lib/scheduler/Scheduler.ts`. 

`assignNextWorkspace` has the potential for an endless loop on line 159:
```
        const assignedWorkspaceId = await fallbackScheduler.assignNextWorkspace(
          userId,
          maybeSuboptimal,
        );
```
I suspect, though have not reproduced, that getting caught here is why it's a good idea to refresh if you've waited to long for your next workspace.

The first heavy submethod of `assignNextWorkspace` is `getActionableWorkspaces` from `server/lib/scheduler/Scheduler.ts`.  The first call is to another resolver, `fetchAllRootWorkspaces` , in which these submethods are the most expensive:

`server/lib/scheduler/index.ts`, `fetchAllRootWorkspaces` line 109
```
const rootWorkspaces = await Workspace.findAll({
        where: {
          parentId: null,
          isArchived: false,
        },
      });
```
Returns about 450 workspaces on my local staging instance. I'd anticipate it's much greater on production. Takes about 5 seconds.

`server/lib/scheduler/index.ts`, `fetchAllRootWorkspaces` line 116

```
      const eligibleRootWorkspaces = await filter(rootWorkspaces, async w => {
        const tree = await Tree.findOne({
          where: {
            rootWorkspaceId: w.id,
          },
        });

        if (!tree) {
          return false;
        }

        const experiments = (await tree.$get("experiments")) as Experiment[];

        return _.some(experiments, e => e.id === experimentId);
      });
```
Returns 45 workspaces locally, may also be much larger on production. Takes about 15 seconds.

A few next steps:
- Copy prod DB and setup locally to get more accurate tests
- Try using deeper filters earlier
- Consider adding another DB field to skip heavy queries

**Comment by zjmiller** [comment]
This all sounds reasonable @andrewschreiber . I would focus on the DB queries and not worry about the endless loop stuff for now (we aren't using fallbacks in the current experiments so it's probably not relevant).

**Comment by zjmiller** [comment]
Another point that might be relevant. Things were initially set up to allow a single workspace to belong to multiple experiments. There was actually the case for a few workspaces, though I'm pretty sure not for any recent ones. It might be that if we can assume a workspace belongs to at most one experiment, it will be possible to set up some of the DB code more efficiently.

**Comment by brachbach** [comment]
I think it's fine to make it so that a tree can only be in one experiment at once. I can maybe imagine cases where it'd be slightly nice to have a tree in more than one experiment at once, but they're very marginal and not worth having any slowdown over.

**Comment by andrewschreiber** [comment]
Here is an interesting page that gives the performance profiles of all DB queries on production:

https://data.heroku.com/datastores/b2ed9b32-2f37-4563-a249-e580d25e5fda#diagnose

It wasn't on my radar, but it looks like our `block` queries take up the most total DB time.

**Comment by Mati-Roy** [comment]
either I don't have access or the link doesn't work

**Comment by andrewschreiber** [comment]
Do you have access to Ought's Heroku account?

**Comment by andrewschreiber** [comment]
Here is a screenshot of our two most expensive queries:
![image](https://user-images.githubusercontent.com/1892071/66101680-8e653b00-e564-11e9-9240-5035b8000ee6.png)

Unfortunately it's abstracted at the SQL level, not the GraphQL level, so we need to do a little investigation to figure out what's triggering them. I figure the `block` query is used rather broadly, as if you search `blocks {` in Mosaic, you'll find 18 results across ~8 GraphQL queries.

**Comment by zjmiller** [comment]
I'm pretty sure the scheduler doesn't use `block` queries though.

This would be relevant for the front page being slow for admins. Though I think the low-hanging fruit there is just loading far fewer workspaces.
