### ISSUE TITLE
For MIB trees, remove the "wait for answer" button

### ISSUE THREAD

**Issue by brachbach** [oughtinc/mosaic#749]
It's not needed and could lead to the tree becoming blocked. See https://docs.google.com/document/d/1k9X1SHYqO7rwFWSxnW9Iwb6mJjpbWUzZQmoTLAT9fEo/edit?ts=5d8921cd#heading=h.6vci0hpntp9c

**Comment by brachbach** [comment]
@zjmiller could you confirm that the button is indeed not needed in MIB trees?

**Comment by zjmiller** [comment]
Yeah, good point. It's not needed in MIB trees.

**Comment by Mati-Roy** [comment]
update: this week, 3 new uncompleted trees became stale, and it seems very likely that 2 of them were caused by clicking "wait for answer" when there was no answer to wait for. a judge even wrote in the scratchpad "Arriving after sQ1 answered. I'm going to come back to this later." I'll confirm with them that that's what actually happened.

for reference, list of uncompleted trees with no stale workspaces: https://docs.google.com/spreadsheets/d/1yXKNu10_-USduzP5eTjQH_kExWauP5siLzAGnST3wVM/edit#gid=395006044

**Comment by zjmiller** [comment]
Looks like it was also the problem with the 3rd tree.

**Comment by Mati-Roy** [comment]
@zjmiller , can you share a screenshot of what you see on Sentry? or even better, give me access to it
